### ISSUE TITLE
TrafficSimulation2.py missing function

### ISSUE THREAD

**Issue by MacTireBan** [ks-moss/472-2023-G3#146]
In TrafficSimulation2.py
     in class TrafficSystem
          in function generateSimpleOutputString()
               call to checkLightState(), function does not yet exist

**Comment by ks-moss** [comment]
Thanks for mentioning the issue. Are those required functions? Can we comment it out?

**Comment by MacTireBan** [comment]
Tony is working on adding the function that's missing.
