### ISSUE TITLE
Work Lists

### ISSUE THREAD

**Issue by ks-moss** [ks-moss/472-2023-G3#147]
**In 3dGraphic2.py**
- Create "Add Bus Stop" button
- The bus doesn't stop for buss-stop
- Right now, all the vehicles run without making turn (left/right). So, all Vehicles may turn when it's at the intersection.

**Comment by L-u-t-o** [comment]
Issue noted. Gus mentioned he will work on getting these implemented.

**Comment by ks-moss** [comment]
Thanks for letting us know
