### ISSUE TITLE
Program crashes after bus stop complete, restart occurs, and bus arrives at light. 

### ISSUE THREAD

**Issue by L-u-t-o** [ks-moss/472-2023-G3#153]
Error seems to lie in BusStopSimulation.py 
Error message: **TypeError: '>' not supported between instances of 'datetime.datetime' and 'int'**

I will try to fix myself first.

**Comment by ks-moss** [comment]
Is it fixed or are you still working on it?

**Comment by L-u-t-o** [comment]
Fixed as far as graphics.py functionality goes.
