### ISSUE TITLE
Need Final Two Consistent Sim Specs

### ISSUE THREAD

**Issue by 050cal** [ks-moss/472-2023-G3#169]
• There is a maximum of one vehicle generator on each road.
• A traffic light must not be within the deceleration distance of another traffic
light (see Appendix B).

I'll follow up with these today. Just thought I would track them here.

**Comment by 050cal** [comment]
Just fo follow up, Angelica mentioned they would be able to complete the final two.

**Comment by angflores** [comment]
Added final two sim specs, however could not test due to NameError issue in 3dGraphics2.py. Logic framework currently under review in latest PR.

**Comment by L-u-t-o** [comment]
I will review PR, thank you for these checks

**Comment by devyngilliam** [comment]
Final two were implemented by Angelica, great work guys!
